# Generated by Django 3.1.2 on 2020-11-17 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, message='Name should atleast have 2 characters')])),
                ('email', models.EmailField(default='ex@ex.com', max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=80, null=True)),
                ('about', models.TextField(max_length=300)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Do Not Specify')])),
                ('subjects', models.CharField(help_text='Subject 1, Subject 2, Subject 3...', max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Length should atleast have 2 characters')])),
                ('cv', models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Please choose a .pdf file.')])),
                ('twitter_link', models.URLField(blank=True, max_length=250, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=250, null=True)),
                ('github_link', models.URLField(blank=True, max_length=250, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=250, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userInfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(2, message='Comment should atleast have 2 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userInfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tutor', 'user', 'id')},
            },
        ),
    ]
