# Generated by Django 3.1.2 on 2020-11-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userInfo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.userinfo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='userInfo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.userinfo'),
        ),
    ]
